---
- name: Gather and display specific Ansible Facts
  hosts: all_nodes
  gather_facts: true
  tasks:
  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts.os_family
  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts
  - name: filter
    setup:
      filter: ansible*
