---
- name: Gather and display specific Ansible Facts
  hosts: all_nodes
  tasks:
    - name: Gather Ansible Facts
      setup:
      register: ansible_facts_output

    - name: Display facts
      debug:
        var: ansible_facts_output.ansible_facts
